### ISSUE TITLE
表の中の禁則処理

### ISSUE THREAD

**Issue by MZ-Gen-Labs** [fuka/asciidoctor-pdf-linewrap-ja#1]
素晴らしいツールをありがとうございます。宮沢と申します。
すみませんが、表の中の文章の禁則処理に関して、どのようにされているか、また対応可能であるか教えていただけませんでしょうか。
表の中の文章に関して禁則処理がされていないように思います。下のサンプルで確認いただけますでしょうか。

借り物の環境ですが、以下に、 asciidoctor-pdf-linewrap-jaを追加した環境で試させていただいています。
https://github.com/htakeuchi/docker-asciidoctor-jp

------------------------------------------------------------------------------------------------------------
sample.adoc
------------------------------------------------------------------------------------------------------------
幾何形状：解析に利用されているパーツやサーフェスを管理します。アセンブリでは、解析実行時のみファイルの材質を変更することもできます。

幾何形状：解析に利用されているパーツやサーフェスを管理します。アセンブリでは、解析実行時のみ、ファイルの材質を変更することもできます。

幾何形状：解析に利用されているパーツやサーフェスを管理します。アセンブリでは、解析実行時にのみ、ファイルの材質を変更することもできます。

[cols="3,7"]
|====
.2+|
|解析条件：解析は解析条件として保管されます。また、一つのファイルで複数の解析条件を作成し切り替えて利用することができます。
|幾何形状：解析に利用されているパーツやサーフェスを管理します。アセンブリでは、解析実行時のみパーツの材質を変更することもできます。
|====

[cols="1"]
|====
|幾何形状：解析に利用されているパーツやサーフェスを管理します。アセンブリでは、解析実行時のみファイルの材質を変更することもできます。
|幾何形状：解析に利用されているパーツやサーフェスを管理します。アセンブリでは、解析実行時にのみ、ファイルの材質を変更することもできます。
|====

|====
|幾何形状：解析に利用されているパーツやサーフェスを管理します。アセンブリでは、解析実行時のみファイルの材質を変更することもできます。
|幾何形状：解析に利用されているパーツやサーフェスを管理します。アセンブリでは、解析実行時にのみ、ファイルの材質を変更することもできます。
|====
------------------------------------------------------------------------------------------------------------

**Comment by fuka** [comment]
バージョン0.4.0で表の中でも禁則処理ができるようにしてみました。
