### ISSUE TITLE
¥の直後に日本語があると¥の代わりに{zwsp}がpdfに出力される

### ISSUE THREAD

**Issue by kn89620** [fuka/asciidoctor-pdf-linewrap-ja#4]
¥と日本語が連続する文字列があると¥の代わりに{zwsp}という文字列がそのままpdfに出力されるので¥のまま出力させたい。
ひとまず、remove_zero_width_space(line)にline.gsub(/\\#{ZERO_WIDTH_SPACE}/, "\\")を追加して回避してます。

**Comment by fuka** [comment]
バージョン0.8.0でバックスラッシュの後にzwspを挿入しないよう修正しました。
